server:
  port: 8081
  servlet:
    contextPath: /core

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5554/exchangeDB"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 10000
      validation-timeout: 10000
      idle-timeout: 10000
      leak-detection-threshold: 10000
      max-lifetime: 3600000
      max-pool-size: 3
      min-idle: 1000
      is-auto-commit: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db.changelog/db.changelog-master.xml
  jackson:
    default-property-inclusion: non_absent
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.springframework: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE